CREATE DATABASE MYMRESPUESTOS;

USE MYMRESPUESTOS;

SELECT * FROM suspensiones;

SELECT DESCRIPCION, MAX(PRECIO_ESTIMADO) MAX_PRECIO, MIN(PRECIO_ESTIMADO) MIN_PRECIO FROM suspensiones GROUP BY DESCRIPCION;

SELECT DESCRIPCION, PRECIO_BASE, PRECIO_ESTIMADO, ((PRECIO_BASE - PRECIO_ESTIMADO) / (PRECIO_BASE)) * 100 DESCUENTO_APLICADO_PORC FROM suspensiones 
WHERE PRECIO_BASE != 0;

SELECT JSON_ARRAYAGG(JSON_OBJECT('DESCRIPCION',DESCRIPCION,'CODIGO',CODIGO_DEL_REPUESTO,'PRECIO_ESTIMADO',PRECIO_ESTIMADO,'PRECIO_BASE',PRECIO_BASE)) FROM suspensiones;


